### ISSUE TITLE
How do I get the order?

### ISSUE THREAD

**Issue by ghost** [justinmc/Rank-Form#1]
After a user sorts the items and presses submit, how is it passed? This isn't necessary, but you you happen to have any sample PHP code? Any help is appreciated. 

Thanks for making this available for free!

**Comment by justinmc** [comment]
Did you figure it out?  Basically the name of the hidden inputs ([here](https://github.com/justinmc/Rank-Form/blob/master/index.html#L29)) change when their rank changes.  So the first one will have `name"0"`, next will have `name="1"`, etc.

I apologize for the lack of good documentation, this is an old project.

**Comment by ghost** [comment]
I figured it out, thanks though (:

**Comment by justinmc** [comment]
Good to hear 👍
